apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: malware-scanner  
spec:
  template:
    metadata:      
      annotations:
        autoscaling.knative.dev/maxScale: '2'
        autoscaling.knative.dev/minScale: '0'        
        run.googleapis.com/sessionAffinity: 'false'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 20
      timeoutSeconds: 300
      serviceAccountName: malware-scanner@candidate-collective-app.iam.gserviceaccount.com
      containers:
      - name: malware-scanner-1
        image: ${IMAGE}
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: CONFIG_JSON
          value: ${CONFIG_JSON}
        resources:
          limits:
            cpu: '1'
            memory: 4Gi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 8080
  traffic:
  - percent: 100
    latestRevision: true
